# Data cleaning

In [49]:
#Import our data to the notebook
import pandas as pd
subcounty_crop_yield_population = pd.read_csv('TABLES/Uganda_Karamoja_Subcounty_Crop_Yield_Population.csv')
district_crop_yield_population = pd.read_csv('TABLES/Uganda_Karamoja_District_Crop_Yield_Population.csv')

In [85]:
#Check the structure of our data
district_crop_yield_population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OBJECTID      7 non-null      int64
 1   NAME          7 non-null      object
 2   POP           7 non-null      int64
 3   Area          7 non-null      int64
 4   S_Yield_Ha    7 non-null      int64
 5   M_Yield_Ha    7 non-null      int64
 6   Crop_Area_Ha  7 non-null      float64
 7   S_Area_Ha     7 non-null      float64
 8   M_Area_Ha     7 non-null      float64
 9   S_Prod_Tot    7 non-null      int64
 10  M_Prod_Tot    7 non-null      int64
dtypes: float64(3), int64(7), object(1)
memory usage: 748.0+ bytes

In [87]:
#check the structure of our data
subcounty_crop_yield_population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OBJECTID        52 non-null     int64
 1   SUBCOUNTY_NAME  52 non-null     object
 2   DISTRICT_NAME   52 non-null     object
 3   POP             52 non-null     int64
 4   Area            52 non-null     int64
 5   Karamoja        52 non-null     object
 6   S_Yield_Ha      52 non-null     float64
 7   M_Yield_Ha      52 non-null     float64
 8   Crop_Area_Ha    52 non-null     float64
 9   S_Area_Ha       52 non-null     float64
 10  M_Area_Ha       52 non-null     float64
 11  S_Prod_Tot      52 non-null     float64
 12  M_Prod_Tot      52 non-null     float64
dtypes: float64(7), int64(3), object(3)
memory usage: 5.4+ KB

In [89]:
#Check duplicates for the subcounty dataset

print(subcounty_crop_yield_population.duplicated().sum())

0

In [91]:
#Check duplicates for the district dataset
print(district_crop_yield_population.duplicated().sum())

0

In [93]:
#Handle missing values
print(district_crop_yield_population.isnull().sum())

OBJECTID        0
NAME            0
POP             0
Area            0
S_Yield_Ha      0
M_Yield_Ha      0
Crop_Area_Ha    0
S_Area_Ha       0
M_Area_Ha       0
S_Prod_Tot      0
M_Prod_Tot      0
dtype: int64

In [59]:
print(subcounty_crop_yield_population.isnull().sum())

OBJECTID          0
SUBCOUNTY_NAME    0
DISTRICT_NAME     0
POP               0
Area              0
Karamoja          0
S_Yield_Ha        0
M_Yield_Ha        0
Crop_Area_Ha      0
S_Area_Ha         0
M_Area_Ha         0
S_Prod_Tot        0
M_Prod_Tot        0
dtype: int64

In [63]:
subcounty_crop_yield_population.describe()

,OBJECTID,POP,Area,S_Yield_Ha,M_Yield_Ha,Crop_Area_Ha,S_Area_Ha,M_Area_Ha,S_Prod_Tot,M_Prod_Tot
count,52.000000,52.000000,5.200000e+01,52.000000,52.000000,52.000000,52.000000,52.000000,5.200000e+01,5.200000e+01
mean,787.865385,28934.692308,5.331913e+08,274.165405,940.259552,2839.646974,2253.143395,536.300569,6.557443e+05,5.500730e+05
std,280.101314,20865.122974,4.913308e+08,118.569907,321.641901,3110.505917,2954.355858,724.092288,9.915839e+05,7.939707e+05
min,263.000000,1418.000000,2.121209e+06,108.156411,0.000000,0.171390,0.130941,0.000000,1.728126e+01,0.000000e+00
25%,597.750000,16558.500000,1.568923e+08,173.034066,743.075879,964.876031,405.394759,79.821743,1.210555e+05,6.087012e+04
50%,810.500000,23053.500000,3.848356e+08,277.255206,1016.684002,1654.265138,1231.824456,326.479336,2.543687e+05,2.896239e+05
75%,982.250000,39461.000000,7.749029e+08,368.246437,1203.548665,3267.564651,2429.985069,740.296675,6.040942e+05,8.114574e+05
max,1320.000000,100919.000000,2.069555e+09,560.313070,1396.991494,13587.990760,12964.499730,3840.698081,4.582294e+06,4.365058e+06

In [61]:
district_crop_yield_population.describe()

,OBJECTID,POP,Area,S_Yield_Ha,M_Yield_Ha,Crop_Area_Ha,S_Area_Ha,M_Area_Ha,S_Prod_Tot,M_Prod_Tot
count,7.000000,7.000000,7.000000e+00,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000e+00,7.000000e+00
mean,61.714286,214943.571429,3.960853e+09,269.285714,986.142857,21094.520379,16737.636651,3983.947082,4.873098e+06,4.085632e+06
std,36.481567,188604.280916,1.781860e+09,119.243049,321.566700,17363.854165,16625.963460,2678.911441,5.743724e+06,2.877188e+06
min,5.000000,90385.000000,1.643583e+09,128.000000,355.000000,5470.068394,2973.423860,1190.050606,6.069440e+05,4.224680e+05
25%,37.000000,114800.500000,3.171069e+09,171.000000,899.500000,5860.128883,4009.522373,1799.997070,1.040529e+06,1.966571e+06
50%,80.000000,146780.000000,3.641540e+09,279.000000,1040.000000,22944.296020,16142.015880,2733.661014,2.211456e+06,3.545558e+06
75%,88.500000,205391.000000,4.362553e+09,343.500000,1206.000000,27247.185510,19890.764085,6484.753740,6.290160e+06,6.288030e+06
max,96.000000,627057.000000,7.373606e+09,449.000000,1297.000000,53032.649450,50247.443900,7394.416334,1.663190e+07,8.122197e+06

In [65]:
district_crop_yield_population

,OBJECTID,NAME,POP,Area,S_Yield_Ha,M_Yield_Ha,Crop_Area_Ha,S_Area_Ha,M_Area_Ha,S_Prod_Tot,M_Prod_Tot
0,92,ABIM,90385,2771977106,449,1040,5470.068394,3277.295971,1848.621855,1471506,1922567
1,96,AMUDAT,101790,1643582836,205,1297,5765.443719,2973.423860,2733.661014,609552,3545558
2,20,KAABONG,627057,7373606003,279,945,28121.672530,20544.194960,7394.416334,5731830,6987723
3,85,KOTIDO,243157,3641539808,331,1148,53032.649450,50247.443900,1751.372284,16631904,2010575
4,5,MOROTO,127811,3570160948,128,355,5954.814048,4741.748776,1190.050606,606944,422468
5,54,NAKAPIRIPIRIT,146780,4216323900,356,1264,26372.698490,19237.333210,6425.788414,6848491,8122197
6,80,NAPAK,167625,4508782023,137,854,22944.296020,16142.015880,6543.719066,2211456,5588336

In [67]:
subcounty_crop_yield_population

,OBJECTID,SUBCOUNTY_NAME,DISTRICT_NAME,POP,Area,Karamoja,S_Yield_Ha,M_Yield_Ha,Crop_Area_Ha,S_Area_Ha,M_Area_Ha,S_Prod_Tot,M_Prod_Tot
0,263,KACHERI,KOTIDO,17244,1067176155,Y,354.207411,1137.467019,7023.533691,6434.342449,528.124229,2.279092e+06,6.007239e+05
1,264,KOTIDO,KOTIDO,52771,597575188,Y,367.890523,1162.996687,13587.990760,12455.592640,824.767081,4.582294e+06,9.592014e+05
2,265,KOTIDO TOWN COUNCIL,KOTIDO,27389,23972401,Y,369.314177,1167.005832,1656.531855,1520.322052,8.561644,5.614765e+05,9.991488e+03
3,266,NAKAPERIMORU,KOTIDO,38775,419111591,Y,283.324569,852.366578,7087.823334,6761.488901,45.721712,1.915696e+06,3.897166e+04
4,267,PANYANGARA,KOTIDO,65704,880955930,Y,373.836926,1283.859882,10398.249390,10111.198130,172.611914,3.779939e+06,2.216095e+05
5,268,RENGEN,KOTIDO,41273,652744859,Y,271.185843,1047.180128,13278.520430,12964.499730,171.585704,3.515789e+06,1.796811e+05
6,591,KAABONG EAST,KAABONG,42221,60801942,Y,160.588525,650.123565,1021.316990,1004.647534,15.660409,1.613349e+05,1.018120e+04
7,592,KAABONG TOWN COUNCIL,KAABONG,38857,13071455,Y,212.210703,1229.213444,175.080527,156.503888,18.526186,3.321180e+04,2.277264e+04
8,593,KAABONG WEST,KAABONG,41454,67612362,Y,208.040518,1056.416068,967.336727,910.254122,56.275355,1.893697e+05,5.945019e+04
9,594,KALAPATA,KAABONG,99203,223116860,Y,209.809352,633.423182,2834.349905,2501.368282,331.225795,5.248105e+05,2.098061e+05
10,595,KAMION,KAABONG,60070,1199409465,Y,259.898246,714.475743,997.161021,411.807001,549.863337,1.070279e+05,3.928640e+05
11,596,KAPEDO,KAABONG,33951,304557831,Y,301.154328,1030.064093,2365.259806,1624.564380,722.649869,4.892446e+05,7.443757e+05
12,597,KATHILE,KAABONG,56870,228457417,Y,312.278615,1125.685462,6890.699234,5997.222911,867.873171,1.872804e+06,9.769522e+05
13,598,KAWALAKOL,KAABONG,37691,1742041261,Y,298.449959,871.612802,3934.432233,2249.777060,1620.876815,6.714459e+05,1.412777e+06
14,599,LOBALANGIT,KAABONG,22907,302572789,Y,386.529819,985.192699,1890.248613,879.002339,1005.877396,3.397606e+05,9.909831e+05
15,600,LODIKO,KAABONG,31820,397700845,Y,164.652061,815.255729,401.797821,324.202666,75.244398,5.338064e+04,6.134343e+04
16,601,LOLELIA,KAABONG,100919,1069331387,Y,285.213427,1273.397362,2700.676313,2039.327583,656.586397,5.816436e+05,8.360954e+05
17,602,LOYORO,KAABONG,16608,1330019236,Y,284.183058,1303.403556,1491.771813,1318.309036,154.682239,3.746411e+05,2.016134e+05
18,603,NAPORE (KARENGA),KAABONG,20394,309577387,Y,295.734350,765.334926,1494.047587,267.559128,1221.532726,7.912642e+04,9.348817e+05
19,604,SIDOK,KAABONG,24092,125330583,Y,285.336294,1396.991494,957.493946,859.649027,97.542243,2.452891e+05,1.362657e+05
20,765,ABIM,ABIM,14377,188613057,Y,501.263249,1183.089648,999.371589,593.531315,259.449330,2.975154e+05,3.069518e+05
21,766,ABIM TOWN COUNCIL,ABIM,11489,115941152,Y,439.750995,1061.151087,788.462800,472.601700,282.613094,2.078271e+05,2.998952e+05
22,767,ALEREK,ABIM,12573,1255760525,Y,520.407672,1259.122045,1266.109868,902.684120,354.449035,4.697637e+05,4.462946e+05
23,768,LOTUKEI,ABIM,18641,191684465,Y,382.868986,1003.303910,698.171218,364.988891,321.847331,1.397429e+05,3.229107e+05
24,769,MORULEM,ABIM,16834,250364895,Y,407.500416,962.958170,925.054130,600.673107,299.151724,2.447745e+05,2.880706e+05
25,810,KARITA,AMUDAT,45015,658008801,Y,193.904842,1286.723173,2513.271830,1358.647499,1100.152370,2.634483e+05,1.415592e+06
26,811,LOROO,AMUDAT,22541,371970302,Y,200.696210,1196.088040,1539.401382,879.668004,658.917612,1.765460e+05,7.881235e+05
27,812,AMUDAT,AMUDAT,30181,596393139,Y,239.047878,1379.045945,1651.998420,676.783266,972.174246,1.617836e+05,1.340673e+06
28,813,AMUDAT TOWN COUNCIL,AMUDAT,4053,17207110,Y,146.117797,861.208491,60.772086,58.325090,2.416786,8.522334e+03,2.081356e+03
29,925,KATIKEKILE,MOROTO,11772,277451997,Y,311.006215,546.140294,145.243518,30.157048,103.277562,9.379029e+03,5.640404e+04
30,926,NADUNGET,MOROTO,42115,596023780,Y,133.667936,591.270355,2480.121900,2406.190665,70.505694,3.216305e+05,4.168793e+04
31,927,TAPAC,MOROTO,21999,622266516,Y,155.869934,211.965635,1111.664207,315.979223,793.237094,4.925166e+04,1.681390e+05
32,928,NORTHERN DIVISION,MOROTO,7161,2738777,Y,131.977698,241.538427,0.322316,0.130941,0.191375,1.728126e+01,4.622440e+01
33,929,SOUTHERN DIVISION,MOROTO,3272,2121209,Y,114.795569,0.000000,0.171390,0.171390,0.000000,1.967487e+01,0.000000e+00
34,978,LOREGAE,NAKAPIRIPIRIT,26644,928683431,Y,384.256293,1114.593607,5759.618906,4622.491870,864.110569,1.776222e+06,9.631321e+05
35,979,NAKAPIRIPIRIT TOWN COUNCIL,NAKAPIRIPIRIT,1418,4673094,Y,482.438793,1257.802716,29.145760,1.339919,27.795767,6.464290e+02,3.496159e+04
36,980,NAMALU,NAKAPIRIPIRIT,25905,553067364,Y,560.313070,1325.254872,5793.507623,2197.572106,3293.749460,1.231328e+06,4.365058e+06
37,981,KAKOMONGOLE,NAKAPIRIPIRIT,15960,312709097,Y,398.979005,1318.261936,3264.534948,2791.837410,457.357605,1.113885e+06,6.029171e+05
38,982,LOLACHAT,NAKAPIRIPIRIT,22801,642401705,Y,334.284302,1225.930541,5079.779088,4364.693411,655.212276,1.459048e+06,8.032447e+05
39,983,LORENGEDWAT,NAKAPIRIPIRIT,9929,435714604,Y,188.699612,795.733280,2008.068169,1917.576345,80.417027,3.618459e+05,6.399050e+04
40,984,NABILATUK,NAKAPIRIPIRIT,27534,499776866,Y,259.454122,1066.204758,3276.653762,3156.538704,87.474549,8.189770e+05,9.326578e+04
41,1023,IRIIRI,NAPAK,46979,1030623258,Y,229.299157,873.452242,5473.443674,1550.944570,3840.698081,3.556303e+05,3.354666e+06
42,1024,LOPEEI,NAPAK,18815,790782350,Y,108.156411,1053.257168,3120.318045,2121.747320,955.264617,2.294806e+05,1.006139e+06
43,1025,LORENGECORA,NAPAK,2503,118997955,Y,184.081197,841.815010,1031.196285,672.121886,358.550335,1.237250e+05,3.018331e+05
44,1026,LOTOME,NAPAK,17834,125857565,Y,128.555598,507.907068,1849.966589,1770.358693,78.035892,2.275895e+05,3.963498e+04
45,1027,MATANY,NAPAK,29495,338252511,Y,130.007687,497.353282,2990.847377,2664.796115,288.329571,3.464440e+05,1.434017e+05
46,1028,NAPAK TOWN COUNCIL,NAPAK,8010,150906375,Y,175.828068,725.813930,792.249273,386.158033,401.173442,6.789742e+04,2.911773e+05
47,1029,NGOLERIET,NAPAK,20790,158887552,Y,134.084089,528.699822,1215.227445,1145.339875,68.124005,1.535719e+05,3.601715e+04
48,1295,NYAKWAE,ABIM,16470,769609687,Y,329.759030,779.225031,792.898789,342.816838,331.111340,1.130469e+05,2.580102e+05
49,1313,LOKOPO,NAPAK,23200,1794470536,Y,120.862232,748.829862,6471.047334,5830.549392,553.543123,7.046932e+05,4.145096e+05
50,1318,RUPA,MOROTO,41493,2069554899,Y,114.270921,699.334309,2217.290717,1989.119508,222.838881,2.272985e+05,1.558389e+05
51,1320,MORUITA,NAKAPIRIPIRIT,16588,839293722,Y,430.557375,1248.955812,1161.390229,185.283445,959.671162,7.977515e+04,1.198587e+06

Now we have noticed that our dataframes are clean and ready for manipulation, we can save it in a new file

In [79]:
district_crop_yield_population.to_excel('district_cleaned.xlsx', index=False)

In [81]:
subcounty_crop_yield_population.to_excel('subcounty_cleaned.xlsx', index=False)